### ISSUE TITLE
learning-rate so sensitive to training result?

### ISSUE THREAD

**Issue by 1576012404** [facebookresearch/torchbeast#5]
train PongNoFrameskip-v4 in example expriment, when i change learning-rate from 0.0004 to 0.0008,i can not train to good result in 30000000 frames.  why? when i choose a larger batch-size, such as 8,training speed slow down,and so how to speed up training?

**Comment by 1576012404** [comment]
why close this issue? i am intersting in  the answer of this question.thank you.

**Comment by heiner** [comment]
Hey 1576012404,

While we're more than happy you chose to use TorchBeast, this issue tracker is for bugs. Yours seems to be better described as miscellaneous questions. I appreciate that RL is hard and hyperparameter dependent. Lots of people are working to improve that situation though so stay tuned and keep reading the literature. :)
